apiVersion: v2
name: gitlab
description: A Helm chart for GitLab
type: application
version: 0.1.1
appVersion: "14.5.2"
maintainers:
- name: sidohaakma
icon: https://about.gitlab.com/images/press/logo/png/gitlab-icon-rgb.png
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.13.14
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 15.6.7
