# Default values for gitlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gitlab/gitlab-ce
  pullPolicy: IfNotPresent
  tag: "14.5.2-ce.0"

auth:
  initialPassword: xxxxx

redis:
  fullnameOverride: redis
  master: 
    persistence: 
      enabled: true
      # existingClaim: data-redis
  architecture: standalone
  auth:
    password: xxxxxxxxx
    existingSecret: ""

postgresql:
  fullnameOverride: postgres
  persistence: 
    enabled: true
    # existingClaim: data-postgres
  postgresqlDatabase: gitlabhq_production
  postgresqlPassword: xxxxxxxxx
  existingSecret: ""
  image:
    tag: 12.9.0-debian-10-r35

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi
  existingClaim: 
    # data: data-gitlab
    # config: config-gitlab
    # logs: logs-gitlab

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: gitlab.haakma.org
      paths: 
        - path: /

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
