apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitlab
  name: config-gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: fill-in-volume-name