apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitlab
  name: data-redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeName: fill-in-volume-name